use_frameworks!

platform :ios, '9.0'

target 'ZYTextInputAvoidKeyboard_Example' do
  pod 'ZYTextInputAvoidKeyboard', :path => '../'

  target 'ZYTextInputAvoidKeyboard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
